/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BiitArtist {
        "artist": any;
        "backgroundColor": string;
        "buttonBgColor": string;
        "buttonBgHoverColor": string;
        "buttonTextColor": string;
        "events": [];
        "fontFamily": string;
        "textColor": string;
        "textHoverColor": string;
    }
}
declare global {
    interface HTMLBiitArtistElement extends Components.BiitArtist, HTMLStencilElement {
    }
    var HTMLBiitArtistElement: {
        prototype: HTMLBiitArtistElement;
        new (): HTMLBiitArtistElement;
    };
    interface HTMLElementTagNameMap {
        "biit-artist": HTMLBiitArtistElement;
    }
}
declare namespace LocalJSX {
    interface BiitArtist {
        "artist"?: any;
        "backgroundColor"?: string;
        "buttonBgColor"?: string;
        "buttonBgHoverColor"?: string;
        "buttonTextColor"?: string;
        "events"?: [];
        "fontFamily"?: string;
        "textColor"?: string;
        "textHoverColor"?: string;
    }
    interface IntrinsicElements {
        "biit-artist": BiitArtist;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "biit-artist": LocalJSX.BiitArtist & JSXBase.HTMLAttributes<HTMLBiitArtistElement>;
        }
    }
}
